fix: add configuration option for whether to plot
Currently, we always plot at hardcoded timesteps for `online_deployment`
regardless of whether this is appropriate for a particular experiment.

This is causing some experiments (e.g. `saturation.yaml`) to error out
due to:
```
File "/home/andy/Projects/rlcore/core-rl/corerl/agent/utils.py", line 99, in get_test_state_qs_and_policy_params
  actor_alphas, actor_betas = agent.actor.model.get_dist_params(test_states)
                                ^^^^^^^^^^^^^^^^^
AttributeError: 'NetworkActor' object has no attribute 'model'
```